@startuml
set separator none
title tellbill - Тарификатор звонков - Components

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<openSwitch>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  shadowing false
}
skinparam rectangle<<tellbill.Тарификаторзвонков.Радиуссервер>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam rectangle<<tellbill.Тарификаторзвонков.РепозиторийCDR>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam database<<tellbill.Хранилищесостояний>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  shadowing false
}
skinparam rectangle<<tellbill.Тарификаторзвонков>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

rectangle "==openSwitch\n<size:10>[Software System]</size>\n\nТелефонный коммутатор" <<openSwitch>> as openSwitch
database "==Хранилище состояний\n<size:10>[Container: posgresql]</size>\n\nDatabase" <<tellbill.Хранилищесостояний>> as tellbill.Хранилищесостояний

rectangle "Тарификатор звонков\n<size:10>[Container: typescript]</size>" <<tellbill.Тарификаторзвонков>> {
  rectangle "==Репозиторий CDR\n<size:10>[Component]</size>" <<tellbill.Тарификаторзвонков.РепозиторийCDR>> as tellbill.Тарификаторзвонков.РепозиторийCDR
  rectangle "==Радиус сервер\n<size:10>[Component]</size>" <<tellbill.Тарификаторзвонков.Радиуссервер>> as tellbill.Тарификаторзвонков.Радиуссервер
}

tellbill.Тарификаторзвонков.Радиуссервер .[#707070,thickness=2].> tellbill.Тарификаторзвонков.РепозиторийCDR : "<color:#707070>Сохраняет звонки"
tellbill.Тарификаторзвонков.РепозиторийCDR .[#707070,thickness=2].> tellbill.Хранилищесостояний : "<color:#707070>Сохраняет звонки"
openSwitch .[#707070,thickness=2].> tellbill.Тарификаторзвонков.Радиуссервер : "<color:#707070>Тарифицирует звонок"
@enduml