@startuml
set separator none
title tellbill - AdminApiFront - Components

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<tellbill.AdminApiBackend>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  shadowing false
}
skinparam rectangle<<tellbill.AdminApiFront.httpсервер>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam person<<Администраторузла>> {
  BackgroundColor #dddddd
  FontColor #ffffff
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<tellbill.AdminApiFront.Репозиторийпользователей>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam rectangle<<tellbill.AdminApiFront.авторизацияпользователя>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam rectangle<<tellbill.AdminApiFront>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

person "==Администратор узла\n<size:10>[Person]</size>" <<Администраторузла>> as Администраторузла
rectangle "==AdminApiBackend\n<size:10>[Container: typescript]</size>" <<tellbill.AdminApiBackend>> as tellbill.AdminApiBackend

rectangle "AdminApiFront\n<size:10>[Container: typescript]</size>" <<tellbill.AdminApiFront>> {
  rectangle "==http сервер\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.httpсервер>> as tellbill.AdminApiFront.httpсервер
  rectangle "==авторизация пользователя\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.авторизацияпользователя>> as tellbill.AdminApiFront.авторизацияпользователя
  rectangle "==Репозиторий пользователей\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Репозиторийпользователей>> as tellbill.AdminApiFront.Репозиторийпользователей
}

tellbill.AdminApiFront.авторизацияпользователя .[#707070,thickness=2].> tellbill.AdminApiFront.Репозиторийпользователей : "<color:#707070>"
tellbill.AdminApiFront.httpсервер .[#707070,thickness=2].> tellbill.AdminApiFront.авторизацияпользователя : "<color:#707070>"
tellbill.AdminApiFront.Репозиторийпользователей .[#707070,thickness=2].> tellbill.AdminApiBackend : "<color:#707070>"
Администраторузла .[#707070,thickness=2].> tellbill.AdminApiFront.httpсервер : "<color:#707070>Смотрит ЛК"
@enduml