@startuml
set separator none
title tellbill - AdminApiFront - Components

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<tellbill.AdminApiBackend>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.pagecontroller>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam person<<Администраторузла>> {
  BackgroundColor #dddddd
  FontColor #ffffff
  BorderColor #9a9a9a
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Отчеты>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.РепозиторийОтчетов>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Репозиторийабонентов>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Репозиторийоператоров>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Репозиторийпользователей>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Репозиторийпрайслистов>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Управлениеабонентамисписоксвойства>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Управлениеоператорамисписоксвойства>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.Управлениепрайслистамисписоксвойства>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam component<<tellbill.AdminApiFront.авторизацияпользователя>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  shadowing false
}
skinparam rectangle<<tellbill.AdminApiFront>> {
  BorderColor #2e6295
  FontColor #2e6295
  shadowing false
}

person "==Администратор узла\n<size:10>[Person]</size>" <<Администраторузла>> as Администраторузла
rectangle "==AdminApiBackend\n<size:10>[Container: typescript]</size>" <<tellbill.AdminApiBackend>> as tellbill.AdminApiBackend

rectangle "AdminApiFront\n<size:10>[Container: typescript]</size>" <<tellbill.AdminApiFront>> {
  component "==Отчеты\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Отчеты>> as tellbill.AdminApiFront.Отчеты
  component "==Репозиторий Отчетов\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.РепозиторийОтчетов>> as tellbill.AdminApiFront.РепозиторийОтчетов
  component "==page controller\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.pagecontroller>> as tellbill.AdminApiFront.pagecontroller
  component "==авторизация пользователя\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.авторизацияпользователя>> as tellbill.AdminApiFront.авторизацияпользователя
  component "==Репозиторий пользователей\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Репозиторийпользователей>> as tellbill.AdminApiFront.Репозиторийпользователей
  component "==Управление абонентами список/свойства\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Управлениеабонентамисписоксвойства>> as tellbill.AdminApiFront.Управлениеабонентамисписоксвойства
  component "==Репозиторий абонентов\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Репозиторийабонентов>> as tellbill.AdminApiFront.Репозиторийабонентов
  component "==Управление операторами список/свойства\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Управлениеоператорамисписоксвойства>> as tellbill.AdminApiFront.Управлениеоператорамисписоксвойства
  component "==Репозиторий операторов\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Репозиторийоператоров>> as tellbill.AdminApiFront.Репозиторийоператоров
  component "==Управление прайслистами список/свойства\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Управлениепрайслистамисписоксвойства>> as tellbill.AdminApiFront.Управлениепрайслистамисписоксвойства
  component "==Репозиторий прайслистов\n<size:10>[Component]</size>" <<tellbill.AdminApiFront.Репозиторийпрайслистов>> as tellbill.AdminApiFront.Репозиторийпрайслистов
}

tellbill.AdminApiFront.pagecontroller .[#707070,thickness=2].> tellbill.AdminApiFront.Управлениепрайслистамисписоксвойства : "<color:#707070>"
tellbill.AdminApiFront.Отчеты .[#707070,thickness=2].> tellbill.AdminApiFront.РепозиторийОтчетов : "<color:#707070>"
tellbill.AdminApiFront.pagecontroller .[#707070,thickness=2].> tellbill.AdminApiFront.Отчеты : "<color:#707070>"
tellbill.AdminApiFront.Репозиторийпользователей .[#707070,thickness=2].> tellbill.AdminApiBackend : "<color:#707070>"
tellbill.AdminApiFront.Репозиторийабонентов .[#707070,thickness=2].> tellbill.AdminApiBackend : "<color:#707070>"
tellbill.AdminApiFront.Репозиторийоператоров .[#707070,thickness=2].> tellbill.AdminApiBackend : "<color:#707070>"
tellbill.AdminApiFront.Репозиторийпрайслистов .[#707070,thickness=2].> tellbill.AdminApiBackend : "<color:#707070>"
tellbill.AdminApiFront.РепозиторийОтчетов .[#707070,thickness=2].> tellbill.AdminApiBackend : "<color:#707070>"
Администраторузла .[#707070,thickness=2].> tellbill.AdminApiFront.pagecontroller : "<color:#707070>Смотрит ЛК"
tellbill.AdminApiFront.авторизацияпользователя .[#707070,thickness=2].> tellbill.AdminApiFront.Репозиторийпользователей : "<color:#707070>"
tellbill.AdminApiFront.pagecontroller .[#707070,thickness=2].> tellbill.AdminApiFront.авторизацияпользователя : "<color:#707070>"
tellbill.AdminApiFront.Управлениеабонентамисписоксвойства .[#707070,thickness=2].> tellbill.AdminApiFront.Репозиторийабонентов : "<color:#707070>"
tellbill.AdminApiFront.pagecontroller .[#707070,thickness=2].> tellbill.AdminApiFront.Управлениеабонентамисписоксвойства : "<color:#707070>"
tellbill.AdminApiFront.Управлениеоператорамисписоксвойства .[#707070,thickness=2].> tellbill.AdminApiFront.Репозиторийоператоров : "<color:#707070>"
tellbill.AdminApiFront.pagecontroller .[#707070,thickness=2].> tellbill.AdminApiFront.Управлениеоператорамисписоксвойства : "<color:#707070>"
tellbill.AdminApiFront.Управлениепрайслистамисписоксвойства .[#707070,thickness=2].> tellbill.AdminApiFront.Репозиторийпрайслистов : "<color:#707070>"
@enduml