addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.3.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"             % "0.9.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"      % "1.9.12")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"             % "0.13.0")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"             % "2.2.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.14.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.3.2")
