@startuml

participant Коммутатор order 10
participant Маршрутизатор order 20
participant Аккаунтинг order 30
participant Тарификатор order 40
participant БД order 50

== Авторизация/Маршрутизация ==

Коммутатор -> Маршрутизатор : Запрос авторизации.\nПередает origTrunk, NumA,NumB
activate Маршрутизатор

Маршрутизатор -> Коммутатор: Можно/нельзя? Если можно,\nто в какой транк.
deactivate Маршрутизатор

Коммутатор -> Аккаунтинг: Сообщает начало звонка

Коммутатор -> Аккаунтинг: Сообщает конец звонка
activate Аккаунтинг
Аккаунтинг -> БД: Cохраняет CDR
deactivate Аккаунтинг

== Тарификация ==

Тарификатор <- БД: Загружает новые CDR
activate Тарификатор
Тарификатор -> БД: Сохраняет рассчитанные плечи
deactivate Тарификатор

@enduml