@startuml

participant Коммутатор order 10
participant Маршрутизатор order 20
participant Аккаунтинг order 30
participant Тарификатор order 40
participant БД order 50

== Авторизация/Маршрутизация ==

Коммутатор -> Маршрутизатор : Запрос авторизации.\nПередает origTrunk, NumA,NumB
activate Маршрутизатор

Маршрутизатор <- БД : вычисление контрагента
Маршрутизатор <- БД : проверка статуса котрагента
Маршрутизатор <- БД : Вычисление возможных маршрутов
Маршрутизатор <- БД : Выбор маршрутов для ответа.

Маршрутизатор -> Коммутатор: Можно/нельзя? Маршрут звонка.
deactivate Маршрутизатор

Коммутатор -> Аккаунтинг: Сообщает начало звонка

Коммутатор -> Аккаунтинг: Сообщает конец звонка
activate Аккаунтинг
Аккаунтинг -> БД: Cохраняет CDR
deactivate Аккаунтинг

== Тарификация ==

Тарификатор <- БД: Загружает новые CDR
activate Тарификатор
Тарификатор -> БД: расчитывает оригинационное плечо звонка
Тарификатор -> БД: расчитывает терминационное плечо звонка
deactivate Тарификатор

@enduml