@startmindmap
* Диплом
** Backend
***[#lightgreen] Rest-интерфейс к сущностям БД <<green>>
**** Разбить на подразделы
*** Механизм аутиндетификации и авторизации
*** Accouting
****[#lightgreen] Скрипт создания тестовых звонков (эмуляция фиксации CDR)
**** Функция превращения Cdr->RAW
**** Rest-Метод тестовой биллингации Cdr->Raw
**** Служба фоновой биллингации поступающих звонков Cdrs->RAWs
*** Auth
**** Метод обрабоки запроса маршрутизации
**** Скрипт эмулятор коммутатора (Делает запрос, получает маршрут, отправляет в нужный транк)
*** Тестирование
**** Авторизация звонка
**** Биллингация звонка
*** служба биллинга. превращение CDR->RAW

** Front
*** Пробный CRUD к любой сущности
*** Страничка логина
*** Разобраться как делать меню в разделе
*** Админская часть
**** crud-клиенты
**** сrud-транки
**** сrud-прайслисты
**** сrud-услуги номера
**** сrud-услуги транк
**** Просмотр звонков
**** Тест маршутизации
**** Тест биллингации
*** Клиентская часть.
**** баланс счета
**** принадлежащие номера
**** выполненные звонки
**[#lightgreen] dev-окружение
** prod-окружение
**[#lightgreen] база данных
***[#lightgreen] тестовые данные
** тестирование
** Документы
*** 1 ?
*** 2 ?


@endmindmap