ARG COMPOSE_PROJECT_NAME
FROM ${COMPOSE_PROJECT_NAME}-base:latest

# Копируем зависимости
#COPY package*.json ./
#RUN npm install

# Копируем исходный код
#COPY . .

# Сервис-специфичные настройки

CMD ["sleep", "infinity"]

#EXPOSE 3000 9229